### ISSUE TITLE
Končan projekt

### ISSUE THREAD

**Issue by DavidRozman** [DavidRozman/APPR-2020-21#6]
Tako, naredil sem še popravek na graf4 , v Binderju mi pravilno tudi prevede poročilo. Kodo sem ročno posodobil na githubu. Vse deluje kot sem si zamislil.

**Comment by jaanos** [comment]
V redu, bom dodal povezavo na repozitorij za zagovore. Če se še nisi, se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

**Comment by DavidRozman** [comment]
Velja. Hvala še enkrat za vso pomoč.

**Comment by DavidRozman** [comment]
Malce sem še polepšal kodo, tako da lahko posodobite.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
